/* Generated By:JJTree&JavaCC: Do not edit this line. WggSimPLParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WggSimPLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int ARROW = 9;
  /** RegularExpression Id. */
  int LEFTB = 10;
  /** RegularExpression Id. */
  int RIGHTB = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int LET = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int FST = 21;
  /** RegularExpression Id. */
  int SND = 22;
  /** RegularExpression Id. */
  int HEAD = 23;
  /** RegularExpression Id. */
  int TAIL = 24;
  /** RegularExpression Id. */
  int SEMI = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int FUN = 27;
  /** RegularExpression Id. */
  int WGGPRINT = 28;
  /** RegularExpression Id. */
  int EQUAL = 29;
  /** RegularExpression Id. */
  int GT = 30;
  /** RegularExpression Id. */
  int LT = 31;
  /** RegularExpression Id. */
  int OR = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int PLUS = 34;
  /** RegularExpression Id. */
  int MINUS = 35;
  /** RegularExpression Id. */
  int STAR = 36;
  /** RegularExpression Id. */
  int SLASH = 37;
  /** RegularExpression Id. */
  int LANG = 38;
  /** RegularExpression Id. */
  int NOT = 39;
  /** RegularExpression Id. */
  int INT = 40;
  /** RegularExpression Id. */
  int BOOL = 41;
  /** RegularExpression Id. */
  int NIL = 42;
  /** RegularExpression Id. */
  int NOP = 43;
  /** RegularExpression Id. */
  int IDENTIFIER = 44;
  /** RegularExpression Id. */
  int LETTER = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\":=\"",
    "\"let\"",
    "\"in\"",
    "\"if\"",
    "\"then\"",
    "\"end\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"fst\"",
    "\"snd\"",
    "\"head\"",
    "\"tail\"",
    "\";\"",
    "\",\"",
    "\"fun\"",
    "\"wggprint\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"or\"",
    "\"and\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"not\"",
    "<INT>",
    "<BOOL>",
    "\"nil\"",
    "\"()\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"::\"",
  };

}
