/* Generated By:JavaCC: Do not edit this line. WggSimPLParserTreeConstants.java Version 5.0 */
package javacc;

public interface WggSimPLParserTreeConstants
{
  public int JJTCONDITIONALNODE = 0;
  public int JJTVARIABLE = 1;
  public int JJTSEQUENCE = 2;
  public int JJTANONYMOUSFUNCTION = 3;
  public int JJTASSIGNEXPRESSION = 4;
  public int JJTLISTEXPRESSION = 5;
  public int JJTADDOREXPRESSION = 6;
  public int JJTADDOR_OP = 7;
  public int JJTCONDEXPRESSION = 8;
  public int JJTCOND_OP = 9;
  public int JJTADDSUBEXPRESSION = 10;
  public int JJTADDSUB_OP = 11;
  public int JJTMULDIVEXPRESSION = 12;
  public int JJTMULDIV_OP = 13;
  public int JJTUOPEXPRESSION = 14;
  public int JJTUOP = 15;
  public int JJTPRINTEXP = 16;
  public int JJTVINT = 17;
  public int JJTVBOOL = 18;
  public int JJTVNIL = 19;
  public int JJTVNOP = 20;
  public int JJTPAIREXP = 21;
  public int JJTAPPEXP = 22;
  public int JJTLETEXP = 23;
  public int JJTIFEXP = 24;
  public int JJTWHILEEXP = 25;
  public int JJTBRAEXP = 26;


  public String[] jjtNodeName = {
    "ConditionalNode",
    "Variable",
    "Sequence",
    "AnonymousFunction",
    "AssignExpression",
    "ListExpression",
    "AddOrExpression",
    "AddOr_Op",
    "CondExpression",
    "Cond_Op",
    "AddSubExpression",
    "AddSub_Op",
    "MulDivExpression",
    "MulDiv_Op",
    "UopExpression",
    "Uop",
    "PrintExp",
    "VInt",
    "VBool",
    "VNil",
    "VNop",
    "PairExp",
    "AppExp",
    "LetExp",
    "IfExp",
    "WhileExp",
    "BraExp",
  };
}
/* JavaCC - OriginalChecksum=32f2d3ca524ffaa2719a17baa5c35bd5 (do not edit this line) */
