/* Generated By:JavaCC: Do not edit this line. WggSimPLParserVisitor.java Version 6.0_1 */
package javacc;

public interface WggSimPLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=031cf27a1829c4245904a8bf6475e789 (do not edit this line) */
