/* Generated By:JavaCC: Do not edit this line. WggSimPLParserVisitor.java Version 5.0 */
package javacc;

public interface WggSimPLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=80507df156b40084e9a230e9bbdf14f8 (do not edit this line) */
