/* Generated By:JavaCC: Do not edit this line. WggSimPLParserDefaultVisitor.java Version 6.0_1 */
package javacc;

public class WggSimPLParserDefaultVisitor implements WggSimPLParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=7f2fea4624582d005c5740c004ef56e2 (do not edit this line) */
